name: build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Initialize Energy Estimation
        uses: green-coding-berlin/eco-ci-energy-estimation@782dd4a31bc426a6ae26a7b08d89af454b10ffc0 # v5.3.0
        with:
          task: start-measurement

      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout Repo Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@782dd4a31bc426a6ae26a7b08d89af454b10ffc0 # v5.3.0
        with:
          task: get-measurement
          label: 'repository checkout'

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'package.json'

      - name: Npm install
        run: npm ci
      - name: Npm build
        run: npm run build --if-present

      - name: Checkout Repo Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@782dd4a31bc426a6ae26a7b08d89af454b10ffc0 # v5.3.0
        with:
          task: get-measurement
          label: 'Npm activities'

      - name: Show Energy Results
        uses: green-coding-berlin/eco-ci-energy-estimation@782dd4a31bc426a6ae26a7b08d89af454b10ffc0 # v5.3.0
        with:
          task: display-results
